# LOCAL DOCKER VERSION #################
version : '3.11'

services:
    app:
        build:
            context: ../../.. #risky_overcooked
            dockerfile: ./risky_overcooked/src/risky_overcooked_webserver/server/Dockerfile_Local
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-master}"
                GRAPHICS: "${GRAPHICS:-risky_overcooked_graphics_v1.js}"
                SRC_PATH: "${SRC_PATH:-risky_overcooked/src}"
            shm_size: "5gb"
        shm_size: "5gb"
        environment:
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "80:5000"
        volumes:
            - data:/app/data
volumes:
  data: